# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Brett McAlpine
title: Senior Research Engineer
email: brettmcalpine@gmail.com
website: brettmcalpine.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  brettmcalpine
linkedin_username: brettstuartmcalpine

# Additional icon links
additional_links:
- title: Projects
  icon: fas fa-wrench
  url: brettmcalpine.github.io/projects.html
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior research engineer. I make many automatic machines and occasionally write code.

  I am most skilled in: <mark>Solidworks</mark> and <mark>making Arduinos work harder than they should</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TOMRA
        link: tomra.com
        # link_text: boringcompany.com
        sub_title: Senior Research Engineer
        caption: 2015 - Present
        quote: >
          Fruit sorting machines, peripherals, controls, analytics
        description: | # this will include new lines to allow paragraphs
          The goal is to experience what the customer experiences by going to their facilities and taking on their gripes, ideas and frustrations first hand then designing machines, processes and/or imagining new technologies that would make the biggest impact to their business or the industry.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Massey University
        caption: 2012 - 2014
        sub_title: BEng with Homours (Mechatronics)
        #quote: >
        #   A quote about Massey?
        description: | # this will include new lines to allow paragraphs
          After moving to NZ I completed my studies in Engineering
          I spent a lot of my free time as a member of the *Albany Massey Engineering Student Society*
      - layout: left
        title: University of Cape Town
        caption: 2008 - 2010
        sub_title: BEng (Mechanical Engineering)

  - title: Outside of work
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Home automation
      - Beach

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
